#spring.application.name=Gateway
spring:
  application:
    name: Gateway

  boot:
    admin:
      client:
        url: http://localhost:1111/

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

  management:
    tracing:
      sampling:
        probability: 1.0

  cloud:
    gateway:
      routes:
        - id: Welcome-Service
          uri: lb://WELCOME-SERVICE
          predicates:
            - Path=/welcome
        - id: Greet
          uri: lb://GREET
          predicates:
            - Path=/greet

server:
  port: 3333

  spring:
    cloud:
      gateway:
        discovery:
          locator:
            enabled: true